[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#111111"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false
