[theme]
primaryColor = "#087e82"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f5f7"
textColor = "#18323f"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false
